yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return str(self.title)


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Изложите свои мысли'
                  ' в этом поле и поделитесь ими с миром.'
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Группа поста',
        help_text='Каждый пост может относиться'
                  ' к некоторой группе или нет.',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ["-pub_date"]

    def __str__(self):
        return str(self.text[:15])


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name='Пост',
        help_text='Пост под которым оставляется комментарий',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Оставьте комментарий'
    )
    created = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Подписчик',
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        verbose_name='Блогер',
        on_delete=models.CASCADE,
        related_name='following',
    )

    def __str__(self):
        return f'Подписка {self.user} на {self.auth}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

yatube/posts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page


from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm
from .utils import pagination


@cache_page(20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.select_related('group')
    page_obj = pagination(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    template = 'posts/index.html'
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = pagination(request, posts)
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=user)
    post_count = posts.count()
    page_obj = pagination(request, posts)
    if request.user.is_authenticated:
        following = (Follow.objects.
                     filter(user=request.user, author=user).exists())
    else:
        following = False
    context = {
        'author': user,
        'page_obj': page_obj,
        'post_count': post_count,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    context = {'form': form}
    if not form.is_valid():
        return render(request, 'posts/create_post.html', context)
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', post.author)


@login_required
def post_edit(request, post_id):
    edit_post = get_object_or_404(Post, id=post_id)
    is_edit = True
    template = 'posts/create_post.html'
    if request.user != edit_post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None,
                    instance=edit_post,
                    files=request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    post_id = edit_post.pk
    return render(request,
                  template,
                  {'form': form, 'is_edit': is_edit, 'post_id': post_id})


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.select_related('author').filter(
        author__following__user=request.user)
    page_obj = pagination(request, posts)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    '''Подписка на блогера'''
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    '''Отписка от блогера'''
    follow = get_object_or_404(Follow,
                               user=request.user,
                               author__username=username)
    follow.delete()
    return redirect("posts:profile", username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %} 
{% load user_filters %}
{% block title %}

{% if is_edit %}
Редактировать запись
{% else %}
Добавить запись
{% endif %}
{%endblock %}

{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Добавить запись
          {% endif %}             
        </div>

        <div class="card-body">  
            <form action=
            {% if is_edit %}
              {% url 'posts:post_edit' post_id %} 
             {% else %}
              {% url 'posts:post_create' %}
             {% endif %}
            method="post" enctype="multipart/form-data">
           
              {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger" >*</span>
                  {% endif %}                 
                </label>

              {{ field|addclass:'form-control' }}

              {% if field.help_text %}
                <small id="id_text-help" class="form-text text-muted">
                {{field.help_text|safe}}
                </small>
              {% endif %}
              </div> 
            {% endfor %}          
            
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Добавить
                {% else %}
                  Сохранить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %} 
{% load thumbnail %}
{% block title %} 
  Список любимых
{%endblock %}

{% block content %}
{% include 'posts/includes/switcher.html' %}
<div class="container py-5">
  <h1>Список постов ваших любимых авторов</h1>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>Автор: {{ post.author }} </li>
        <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %} 
    </article>
    {% if not forloop.last %}
      <hr />
    {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} 
  Записи сообщества {{ group }}
{% endblock %} 

{% block content %} 
<div class="container py-5">
  <h1> {{ group }} </h1>
  <p> {{ group.description }} </p>
  {% for post in page_obj %}
    {% if post.group == group %}
    <article>
      <ul>
        <li>Автор: {{ post.author.get_full_name }}</li>
        <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
      </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
    </article>
    {% if not forloop.last %}<hr />{% endif %}
    {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %} 
{% load thumbnail %}
{% block title %} 
Последние обновления на сайте
{%endblock %}

{% block content %}
{% include 'posts/includes/switcher.html' %}
<div class="container py-5">
  <h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>Автор: {{ post.author }} </li>
        <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %} 
    </article>
    {% if not forloop.last %}
      <hr />
    {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %} 
{% load thumbnail %}

{% block title %} 
  Пост {{ post.text|slice:":30" }}
{%endblock %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{post.pub_date|date:"d E Y"}} 
        </li>
        {% if post.group %} 
        <li class="list-group-item">
          Группа: {{post.group.slug}}
          <a href={% url 'posts:group_list' post.group.slug %}>
            все записи группы
          </a>
        </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.username }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.count}}</span>
        </li>
        <li class="list-group-item">
          <a href={% url 'posts:profile' post.author.username %}>
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      
      <p>
       {{ post.text }} 
      </p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
    {% if request.user == post.author %}
    <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
      Редактировать запись
    </a>
    {% endif %}
      
    </article>
  </div>
  {% include 'comment.html' %} 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %} 
{% load thumbnail %}
{% block title %} 
  Профайл пользователя {{ author }}
{%endblock %}

{% block content %}
<div class="container py-5">        
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.username }}</h1>
    <h3>Всего постов: {{ post_count }}</h3>
    {% if user != author%}
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
     {% endif %}
     {% endif %}
  </div>
    {% for post in page_obj %} 
    <article>
      <ul>
        <li>
          Автор: {{author}}
          <a href={% url 'posts:profile' post.author.username %}>все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
      {{ post.text }}
      </p>
      <a href={% url "posts:post_detail" post.pk %}>подробная информация </a>
    </article>
    {% if post.group%}     
    <a href={% url "posts:group_list" post.group.slug %}>все записи группы</a>
    {% endif %}
    {% if not forloop.last %} 
    <hr>
    {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %} 
</div>
{% endblock %}